import type { Metadata } from "next";
import "./globals.scss";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { JostFont } from "./font/font_Jost";
import ToTopButton from "./components/ToTopButton/ToTopButton";

export const metadata: Metadata = {
  title: "Toy House",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JostFont.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
        <ToTopButton></ToTopButton>
        </body>
    </html>
  );
}
